user nginx;
worker_processes 1;
error_log stderr info; # Log to stderr for docker logs

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout; # Log to stdout for docker logs

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html index.htm; # Ensure index.htm is also considered

        location / {
            try_files $uri $uri/ =404; # Just try to serve files, no fallback to index.html for SPAs
        }
    }
}

