// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiw5WeFjcbO8mNTsavkOVedcFIrvf-JdY',
    appId: '1:1058415112061:web:379ca1de4dbc99161f2614',
    messagingSenderId: '1058415112061',
    projectId: 'thay-golf-app55-402fc',
    authDomain: 'thay-golf-app55-402fc.firebaseapp.com',
    storageBucket: 'thay-golf-app55-402fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2RnDN0A1QXvH0b-RJD9ZOo2--AJmd_Y',
    appId: '1:1058415112061:android:70d91de5a34e443e1f2614',
    messagingSenderId: '1058415112061',
    projectId: 'thay-golf-app55-402fc',
    storageBucket: 'thay-golf-app55-402fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8V_fxjbSu58lxnQQXz2mg9jdyQt9kbQM',
    appId: '1:1058415112061:ios:0f506e0ebc0ceac11f2614',
    messagingSenderId: '1058415112061',
    projectId: 'thay-golf-app55-402fc',
    storageBucket: 'thay-golf-app55-402fc.firebasestorage.app',
    iosBundleId: 'com.example.golfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8V_fxjbSu58lxnQQXz2mg9jdyQt9kbQM',
    appId: '1:1058415112061:ios:0f506e0ebc0ceac11f2614',
    messagingSenderId: '1058415112061',
    projectId: 'thay-golf-app55-402fc',
    storageBucket: 'thay-golf-app55-402fc.firebasestorage.app',
    iosBundleId: 'com.example.golfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiw5WeFjcbO8mNTsavkOVedcFIrvf-JdY',
    appId: '1:1058415112061:web:5ed57a9b2b98cbd81f2614',
    messagingSenderId: '1058415112061',
    projectId: 'thay-golf-app55-402fc',
    authDomain: 'thay-golf-app55-402fc.firebaseapp.com',
    storageBucket: 'thay-golf-app55-402fc.firebasestorage.app',
  );
}
